//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "school_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub school_name: String,
    pub location: String,
    pub logo: Option<String>,
    pub city: Option<String>,
    pub country: String,
    pub school_type: String,
    pub algorithm: String,
    #[sea_orm(unique)]
    pub name_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
